### ISSUE TITLE
 `TimeSeries[]` in `ShotgunModel`, is it necessary?

### ISSUE THREAD

**Issue by mohataher** [patrickzib/SFA#12]

**Comment by mohataher** [comment]
I have removed it in the upcoming commit. Let me know if it's necessary.

**Comment by mohataher** [comment]
When removing it, accuracy failed to nearly half. Not sure what exactly caused that, I reverted all changes and left it in the code for your input here.

**Comment by patrickzib** [comment]
Yes, unfortunately, it is needed. The ShotgunDistance is a 1-nearest neighbor classifier. So, it requires the train samples to make a prediction. These are kept in the TimeSeries[] - array.
