### ISSUE TITLE
`ParallelFor` being static causes issues when running with multiple tests 

### ISSUE THREAD

**Issue by mohataher** [patrickzib/SFA#13]
Whilst refactoring `ParallelFor` is all static and when method `shutdown()` is called, there is no way of reinitialising it back. 

This makes me wonder why it's all static and why it has a `shutdown()` method.

**Comment by patrickzib** [comment]
The idea was to avoid the overhead introduced by creating new threads. Instead the threads are supposed to be pooled. If the class is non-static, new threads would be created every time we have two nested parallel-fors:

```
// new instance
new ParallelFor.withIndex(...) {
  // now there is always a new thread-pool created
  new ParallelFor.withIndex(...) {
  }

// static
ParallelFor.withIndex(...) {
  // here, the thread-pool can be reused
  ParallelFor.withIndex(...) {
  }
```

It is not the very best solution and does have some drawbacks. How would you do it?

**Comment by mohataher** [comment]
My first impression is it's an inherited ability to run tasks in parallel; maybe using default and static methods on java 8 interfaces could do. It needs a little more thinking. Let me get back to you on that.
