### ISSUE TITLE
Generated models for WEASEL are large in size

### ISSUE THREAD

**Issue by mohataher** [patrickzib/SFA#15]
When working with WEASEL, I noticed `save()` method generates a seriously large file to represent the classifier model; approximately 300 MB model for a moderately small dataset. I'm not sure exactly why but my first guess it's saving training data as it's linked somewhere in the dependencies of the objects. 

Do you have any idea?

**Comment by patrickzib** [comment]
Hmm, is there any way to list the sizes of objects using kyro?

There are some possible directions: 

- HashMaps may have been initialized with to large sizes. I am not sure, if there is an easy way to compress (reducing the size of the underlying array) them in the hppc library.

- Liblinear: I am not sure what liblinear actually stores when serialized to disk. It does have a save method though. Maybe if would be better to use it for serialization?

**Comment by patrickzib** [comment]
Update: I found a place in `SFA` to free memory. Could you check again?
