### ISSUE TITLE
Instructions on how to build the project?

### ISSUE THREAD

**Issue by kmundnic** [patrickzib/SFA#23]
I learned Java many years ago, without using the tools that this project uses (Gradle, Maven). It would be great to have instructions on how to build the project, including IDE preference, and what software versions are needed (JDK 10? Gradle version >= 4.8)? Some things that come to mind include:

- Installing Gradle (there are multiple ways)
- How to import the project
- Gradle configuration

**Comment by patrickzib** [comment]
I am really sorry, I missed this post.

I can not reproduce this error. I just downloaded a fresh copy of the repository and imported the project to intellij using the build.gradle file. It worked just fine. Could you give me some more information on how you build the project?

Anyways, I will add information on how to build the project! Thank you for this feedback.

**Comment by wwjd1234** [comment]
I was able to just import the project into InteliJ. InteliJ will then take care of installing the correct Gradle version.
