### ISSUE TITLE
SFATrie search by radius

### ISSUE THREAD

**Issue by assaad** [patrickzib/SFA#27]
Hello patrick, thanks for your effort, 
I am adding the issue here just not to forget, if possible to enable back seach by radius on SFATrie instead of just searching for the K nearest neighbors. 
Cheers!

**Comment by patrickzib** [comment]
Thank you for reminding me, just added the range queries:
https://github.com/patrickzib/SFA/blob/43cfad8696591f4a526ff8372fbbbfee161d215b/src/main/java/sfa/index/SFATrie.java#L593
