### ISSUE TITLE
Python release?

### ISSUE THREAD

**Issue by cbsudux** [patrickzib/SFA#30]
Great Library. Is there a python version?

**Comment by patrickzib** [comment]
Thank you :)
We are working on a port based on [PyTS](https://github.com/johannfaouzi/pyts). PyTS has all classifiers (WEASEL, BOSS, SFA, ...). With some modifications, the PyTS code of WEASEL is very close in accuracy, but still slow, but we are about to close the gap.

**Comment by cbsudux** [comment]
Great! Thanks

**Comment by cbsudux** [comment]
Are you aware of any other fast TS classifiers (in python)?  I'm looking to build something in real time and your inputs would be greatly appreciated.

**Comment by patrickzib** [comment]
Being fast in python is not so trivial. To be write fast python code, you will eventually have to write a cython-port. There is one project that is exactly trying to do so:
https://github.com/alan-turing-institute/sktime

There is also a deep-learning library for time series classification, in case that is an option for you:
https://github.com/hfawaz/dl-4-tsc
