### ISSUE TITLE
README Inconsistent

### ISSUE THREAD

**Issue by wwjd1234** [patrickzib/SFA#31]
HI,

The code in the README seems to be different than how the usage is in the test cases.
For example:

    Score score = weasel.fit(trainSamples);
    Score should be Classifier.Score

Is this correct? If so, should the README be updated?

**Comment by patrickzib** [comment]
Thank you for using Weasel. I am on vacation and will come back to you next week. Thanks

**Comment by wwjd1234** [comment]
No problem thanks

**Comment by patrickzib** [comment]
Thank you for pointing this out. This was in fact wrong, I changed it to Classifier.Score, as you suggested.
