### ISSUE TITLE
Meaning of output

### ISSUE THREAD

**Issue by wwjd1234** [patrickzib/SFA#32]
What is the meaning of the output:

    CBF;WEASEL;0.967;0.998

Specifically the last two numbers. Are they the train and then test accuracy?

**Comment by patrickzib** [comment]
Yes, exactly. The first number is the train accuracy, the second number is the test accuracy.

The corresponding java code ist:
```java  
public String toString() {
      double test = getTestingAccuracy();
      double train = getTrainingAccuracy();
      return this.name + ";" + train + ";" + test;
}
```
