### ISSUE TITLE
Data for histograms

### ISSUE THREAD

**Issue by wwjd1234** [patrickzib/SFA#33]
Is there a way to get the data for the histograms?

- For example WEASEL histogram has weights and words. 

    - How do we get this data to produce the histograms?

**Comment by patrickzib** [comment]
In fact WEASEL has a histogram with frequencies and words. And in a second step it further learns word weights using liblinear.

WEASEL stores the histograms for each sample of the train-data in:
`final BagOfBigrams[] bop = new BagOfBigrams[samples.length];` [Code](https://github.com/patrickzib/SFA/blob/b4bc8819708c9a7da16cca5765fde2c134906f38/src/main/java/sfa/classification/WEASELClassifier.java#L267)

And it stores the histograms for each sample of the test-data in:
`final BagOfBigrams[] bagTest = new BagOfBigrams[samples.length];` [Code](https://github.com/patrickzib/SFA/blob/b4bc8819708c9a7da16cca5765fde2c134906f38/src/main/java/sfa/classification/WEASELClassifier.java#L132)

Thus, if you want to iterate the words and frequencies you can use these `BagOfBigrams`, which are HashMaps. Each one can be iterated like:
`for (LongIntCursor word : bagOfPattern.bob) { ... }`


If you additionally need access to the liblinear weights things become more tricky....
