### ISSUE TITLE
may you share python code for multivariate time series 

### ISSUE THREAD

**Issue by Sandy4321** [patrickzib/SFA#35]
do  you know python code for multivariate time series

**Comment by patrickzib** [comment]
You might have a look at 
- sktime: https://github.com/alan-turing-institute/sktime
- deep learning approaches : https://github.com/hfawaz/dl-4-tsc


Unfortunately, I do not have python code for my multivariate time series classifiers.

**Comment by Sandy4321** [comment]
great thanks
also found this one
https://arxiv.org/pdf/1711.11343v4.pdf
Multivariate Time Series Classification with WEASEL+MUSE
but seems to be it is not python coded

**Comment by Sandy4321** [comment]
this 
https://timeseriesclassification.com/code.php
in java too
