### ISSUE TITLE
Size of training data

### ISSUE THREAD

**Issue by wwjd1234** [patrickzib/SFA#36]
How many examples should we use for training if using our own data? 

Do you have any suggestions? 1000 examples per class?  

What would be small? 50 examples per class? Would the algorithms perform worse in this case?

**Comment by patrickzib** [comment]
I do not have a rule of thumb to be honest. For example, the Coffee dataset contains just 2 classes with only 28 samples in total (14 samples per class). It shows an accuracy of 100% on training and testing data.

Given the UCR datasets, I would consider a few dozens to be small and 1000 example per class to be huge. WEASEL's performance on the smaller datasets is quite good.

If the data is very clean,  a few (dozens of) samples per class are sufficient. If the data is very diverse, more samples might help to improve accuracy.
