### ISSUE TITLE
can you classify categorical data time series ?

### ISSUE THREAD

**Issue by Sandy4321** [patrickzib/SFA#37]
can you classify categorical data time series 
per
Classification and Accuracy: WEASEL and the BOSS ensemble classifier offer state-of-art classification accuracy [2], [3], [4].

**Comment by patrickzib** [comment]
WEASEL and BOSS assume there is a logical order, as similarity is expressed by the distance.

Thus, if there is a logical order defined on your categorical data, it should be fine. Using this logical order, you can map each categorical value to an integer and use WEASEL or BOSS.

temperature 
    low => 1, medium => 2,  high => 3.

But If there is no logical order on your categorical data
   gender: male, female 
then it will likely not work.
