### ISSUE TITLE
Running WeaselMUSE on UCR dataset

### ISSUE THREAD

**Issue by bhaskar-dhariyal** [patrickzib/SFA#39]
Hi Patrick,

I recently read your paper on WEASEL+MUSE, it's a very good work. 

I'm now trying to run WEASEL+MUSE, on UCR multivariate datasets (30 datasets), I think it is not possible to run on ts formatted dataset. Is there a way to run the code from txt files? Am I missing something here?

**Comment by patrickzib** [comment]
Hi, 

thank you! 

I have updated the repository and added an ARFF-Loader:
https://github.com/patrickzib/SFA/blob/afb375e84a7557701a7c1e353e19d9351378d373/src/test/java/sfa/NewMTSArchiveClassificationTest.java#L20

Best 

Patrick
