### ISSUE TITLE
Adding contributors file

### ISSUE THREAD

**Issue by mohataher** [patrickzib/SFA#7]
Shall we have a `contributors.md` file? Something similar to [this](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTORS.txt)?

**Comment by patrickzib** [comment]
Nice Idea, just added a contributors.txt to the project based on [this](https://github.com/google/protobuf/blob/master/CONTRIBUTORS.txt).

I hope, everyone is fine with their real names being listed?

**Comment by ChristianSch** [comment]
Yup! I hope it doesn't attract any spam though :x
